### ISSUE TITLE
模型在rv1126上推理一张图时间长的问题

### ISSUE THREAD

**Issue by zy691218673** [rockchip-linux/rknpu#20]
我买了贵公司一块rv1126的主板，算力在2tops。我的模型是基于yolov3的模型，图片的大小是440*700的分辨率，但发现推理的时间要1s多，然后测试了yolov3的自带例子，耗费765ms，所以想问一下原因......我提供一下模型和推理图，能帮我测试一下具体时间吗？因为想看看性能能不能达到项目的需求（请问一下如何上传模型和推理图）

**Comment by zy691218673** [comment]
> 我买了贵公司一块rv1126的主板，算力在2tops。我的模型是基于yolov3的模型，图片的大小是440*700的分辨率，但发现推理的时间要1s多，然后测试了yolov3的自带例子，耗费765ms，所以想问一下原因......我提供一下模型和推理图，能帮我测试一下具体时间吗？因为想看看性能能不能达到项目的需求（请问一下如何上传模型和推理图）

**Comment by gitbatu** [comment]
Hi,
Did you manage to speed things up?
